### ISSUE TITLE
Utils.py crashes when LAT > 90 east

### ISSUE THREAD

**Issue by Herman031** [nas-/vendee-globe-boat-follower#4]
Hi,

As boats go further east than 90 E, utils.py crashes;

Exception has occurred: ValueError
Latitude must be in the [-90; 90] range.

File "C:\Users\h\Anaconda3\envs\vendee-globe-boat-follower\src\utils.py", line 44, in gcd
    destination = distance.great_circle(nautical=dist).destination(origin, bearing)
  File "C:\Users\h\Anaconda3\envs\vendee-globe-boat-follower\src\utils.py", line 180, in get_data_from_prevpoint
    lon, lat = EarthFunctions.gcd((float(prevpoint.get('LON')), float(prevpoint.get('LAT'))),
  File "C:\Users\h\Anaconda3\envs\vendee-globe-boat-follower\main.py", line 120, in mainloop
    a, b = src.utils.get_data_from_prevpoint(driver, lastdata, item, datafile)
  File "C:\Users\h\Anaconda3\envs\vendee-globe-boat-follower\main.py", line 187, in <module>
    mainloop(**args2)

and

C:\Users\h\AppData\Local\Programs\Python\Python39\lib\site-packages\geopy\point.py:471: UserWarning: Latitude normalization has been prohibited in the newer versions of geopy, because the normalized value happened to be on a different pole, which is probably not what was meant. If you pass coordinates as positional args, please make sure that the order is (latitude, longitude) or (y, x) in Cartesian terms.    
  return cls(*args)

Cheers

**Comment by nas-** [comment]
Thanks for the report. I will have a look later today.

**Comment by nas-** [comment]
Fixed, the problem was [HERE](https://github.com/nas-/vendee-globe-boat-follower/commit/b804220264e4eb9d11d3f87edcb543fd50c8c15f#diff-51246e53255db77c9edad496f074aa1bdbf8dbdc11f89a02040115c9ab4fa7f0R188)

**Comment by Herman031** [comment]
Nice work! Thx.
